### ISSUE TITLE
mmWave Middle Data Query

### ISSUE THREAD

**Issue by rg6g09** [ChristopherLu/milliEgo#1]
Hello,

Thank you for providing this repository, it's a great source of information for a very interesting project.

I have a question regarding the mmWave middle data, provided in your Training/Testing data set, that I'm hoping you can help me understand. I am assuming that this data is a 2D projection of the 3D point cloud. However, can you explain the scaling? Values which I would expect to be 0 at the point of no 3D data are -0.3398 across your entire dataset. Surely, there would have been some function to initialize the shape of the image like img = np.zeros([64,256]), but then your data points would be 0.

Can you perhaps provide the functions you use to create your pointcloud projection data?

Thanks in advance! :)

**Comment by ChristopherLu** [comment]
Sorry for the late response. 

Just added a new file describing how to project the 3d radar point clouds to depth map images. See here: https://github.com/ChristopherLu/milliEgo/blob/7e2f0002b95e2b6360922821e3bb3f76a73ae045/utility/pcl2depth.py#L59

**Comment by rg6g09** [comment]
Hello,

Thank you for the response.

On reviewing this pcl2depth file, there is still a disconnect between this code and the mmwave_middle_data files you have provided. 

- In this pcl2depth code, an image array is initialized to 0 and populated by "dist" points at [x_img, y_img]. In your data, it looks like the array was initialized to -0.033 and all data points normalized to 1 rather than 255. 
- How are you scaling the depth images to 64x256? Based on the TI radar spec for FoV, h_res and v_res, this would result in a very low resolution depth map. So can you comment on what you have set these values as? My guess is you are stretching the images to 64x256?

Thanks again for the help so far, it's greatly appreciated!

Kind Regards

**Comment by ChristopherLu** [comment]
Yes, we resized it to to 64x256 for the sake of FlowNet. Hope this makes thing more clear:

> pano_img = velo_points_2_pano(frame[eff_rows_idx, :], cfg['pcl2depth']['v_res'], cfg['pcl2depth']['h_res'],                                          v_fov, h_fov, cfg['pcl2depth']['max_v'], depth=True)
 >pano_img = cv2.resize(pano_img, (pano_img.shape[1]*4, pano_img.shape[0]*4))

Re your question on normalization, you should find the 'nmalize_depth(val, min_v, max_v)' function in the pcl2depth file.
