### ISSUE TITLE
milliEgo dataset

### ISSUE THREAD

**Issue by vaishali41** [ChristopherLu/milliEgo#2]
Hello, I downloaded the dataset from the link to my computer but I am getting a CRDOWNLOAD FILE after download. The download status shows **Failed - Forbidden** after the download is complete. Is there any alternative to download the dataset? 
![Capture](https://user-images.githubusercontent.com/73190179/117576147-b27aed80-b0b2-11eb-875a-d4d39e0a8542.PNG)

**Comment by ChristopherLu** [comment]
Sorry, I cannot reproduce your issue.

**Comment by vaishali41** [comment]
Hello, I was able to download the dataset after few attempts. Thank you!
