### ISSUE TITLE
Dataset on dropbox has been deleted

### ISSUE THREAD

**Issue by EscapeTHU** [ChristopherLu/milliEgo#8]
I'm currently trying to train milliEgo with your code, but it seems that your dataset published on dropbox has been deleted. I wonder if there's any other way that I can download the dataset? Thanks a lot! Best wishes!
![dropbox](https://user-images.githubusercontent.com/60122724/193988516-cc05fd1b-d2b3-4992-b476-be48642b09db.png)

**Comment by ChristopherLu** [comment]
Hi,

We have integrated the dataset and benchmark of milliEgo into this new project: https://github.com/MAPS-Lab/OdomBeyondVision. You can find the needed dataset download link there.

**Comment by EscapeTHU** [comment]
Thanks for your generous sharing and fast reply. It helps!
